apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: server-app    
  labels:                     
    app: server-app
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: server-app
  template:                   
    metadata:
      labels:                 
        app: server-app
    spec:                     
      containers:
      - name: server-app
        image: ${SERVER_IMAGE_NAME}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080 
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                  
        - name: SPRING_DATASOURCE_USERNAME 
          valueFrom:          
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: server-app    
  labels:                     
    app: server-app
spec:                         
  type: NodePort              
  selector:
    app: server-app   
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080
