def myapp
node ('master') {
    withEnv(['registry = https://768749700464.dkr.ecr.eu-west-2.amazonaws.com',
               'ECRCRED = ecr:eu-west-2:amazon-ecr-jenkins'
               ]) {


    stage('Clone repository') {
        
        checkout scm
    }
     stage('Image') {
            myapp = docker.build("cloudhands" + "/" + "frontend")
            
            }
     stage('Push image') {
     	sh("eval \$(aws ecr get-login --no-include-email | sed 's|https://||')")
        docker.withRegistry('https://768749700464.dkr.ecr.eu-west-2.amazonaws.com', 'ecr:eu-west-2:amazon-ecr-jenkins') {
        myapp.push()
        }
    }

 }

}

